from datetime import datetime

# Define prompts grouped by category
PROMPT_CATEGORIES = {
    "laptops": [
        "best laptops for coding",
        "best laptops for coding", 
        "intel i9 laptops under $1500",
        "lightweight laptops for travel",
        "gaming laptops with RTX 4070",
        "ultrabooks with long battery life"
        "ultrabooks with long battery life",
        "budget-friendly laptops for students",
        "convertible 2-in-1 laptops with stylus support",
        "laptops optimized for video editing",
        "laptops with OLED displays",
        "fanless silent laptops for office use",
        "Linux-compatible laptops for developers",
        "enterprise laptops with top security features",
        "laptops with expandable RAM",
        "portable laptops with multiple USB-C ports",
        "touchscreen laptops under $800",
        "durable laptops for field work",
        "laptops with color-accurate displays for designers",
        "AMD Ryzen laptops for productivity",
        "lightweight gaming laptops with DLSS",
        "eco-friendly laptops made from recycled materials"
    ],
    "cameras": [
        "mirrorless camera with 4K and flip screen",
        "dslr for beginners",
        "best cameras for vlogging under $700",
        "action cameras for sports",
        "budget 4K cameras"
        "budget 4K cameras",
        "full-frame cameras for professional photography",
        "compact cameras with large sensors",
        "cameras with advanced autofocus for wildlife",
        "weather-sealed cameras for adventure",
        "cameras that shoot 10-bit log video",
        "instant cameras with digital hybrid features",
        "cinema cameras for indie filmmakers",
        "cameras supporting dual card slots",
        "360-degree cameras for virtual tours",
        "cameras with wireless live streaming support",
        "entry-level cameras with interchangeable lenses",
        "cameras compatible with vintage lenses",
        "cameras with high dynamic range for landscapes",
        "cameras optimized for astrophotography",
        "point-and-shoot cameras for kids"
    ],
    "tripods": [
        "tripod for wildlife photography",
        "lightweight tripod under $100",
        "heavy-duty tripod for video shooting",
        "travel tripod with ball head",
        "tripods with fluid pan head"
        "tripods with fluid pan head",
        "carbon fiber tripods for professional use",
        "tabletop tripods for content creators",
        "tripods compatible with smartphones",
        "tripods with quick release plates",
        "compact tripods for carry-on luggage",
        "tripods for panoramic photography",
        "tripods with built-in monopod conversion",
        "tripods for macro photography stability",
        "tripods with adjustable center columns",
        "tripods for overhead food photography",
        "tripods designed for uneven terrain",
        "budget-friendly tripod kits with bags",
        "tripods with fluid drag control",
        "tripods with counterweight hooks",
        "tripods for livestreaming setups"
    ],
    "chargers": [
        "best USB-C chargers for iPhone",
        "multi-device charging stations",
        "fast charging car chargers",
        "power banks with fast charging",
        "portable chargers for laptops"
        "portable chargers for laptops",
        "wireless chargers with MagSafe compatibility",
        "GaN chargers with multiple ports",
        "solar-powered chargers for camping",
        "wall chargers with foldable plugs",
        "chargers supporting USB Power Delivery 3.1",
        "travel adapters with universal compatibility",
        "chargers with built-in cables",
        "portable chargers for Nintendo Switch",
        "chargers with LED power indicators",
        "chargers designed for smartwatches",
        "high-wattage chargers for MacBook Pro",
        "compact chargers for minimal desk setups",
        "chargers with surge protection",
        "chargers bundled with braided cables",
        "chargers suitable for airline travel"
    ],
    "apple": [
        "latest apple watch with fitness tracking",
        "airpods pro with noise cancellation",
        "ipad with stylus support",
        "macbook air m2 13 inch",
        "apple tv 4k streaming device"
        "apple tv 4k streaming device",
        "apple refurbished deals with warranty",
        "magSafe accessories for iphone 15",
        "best apple pencil alternatives",
        "macbook pro docking stations",
        "apple homekit compatible devices",
        "apple silicon mac mini for developers",
        "apple watch bands for workouts",
        "icloud storage plans comparison",
        "apple music family plan deals",
        "applecare coverage options",
        "mac accessories for dual monitor setup",
        "apple arcade game recommendations",
        "apple tv remote replacements",
        "best cases for ipad mini",
        "apple-certified refurbished iphones"
    ],
    "audio": [
        "bluetooth speakers under $100",
        "noise cancelling headphones",
        "true wireless earbuds with long battery",
        "soundbars with dolby atmos",
        "budget over-ear headphones"
        "budget over-ear headphones",
        "studio monitors for home recording",
        "portable party speakers with lights",
        "hi-res audio players with streaming",
        "ANC earbuds for commuters",
        "gaming headsets with surround sound",
        "open-back headphones for mixing",
        "wireless earbuds for small ears",
        "smart speakers with voice assistants",
        "audiophile headphones under $500",
        "soundbars with rear speakers",
        "waterproof speakers for showers",
        "bone conduction headphones for running",
        "sleep headphones with soft bands",
        "portable DACs for smartphones",
        "budget desktop speakers for pc"
    ],
    "web_scraping": [
        "python scripts to scrape ecommerce product details",
        "scraping dynamic content with selenium and python",
        "respectful web scraping best practices",
        "parsing complex html tables using beautifulsoup",
        "handling infinite scroll pages during scraping",
        "monitoring website changes with scheduled scrapers",
        "extracting json data from api-like endpoints",
        "scraping job listings using playwright",
        "navigating multi-page pagination with python scrapers",
        "managing authentication and sessions in web scraping",
        "proxy rotation strategies for scraping",
        "headless browser scraping performance tips",
        "scraping websites with captcha challenges",
        "storing scraped data in cloud databases",
        "building scraping pipelines with airflow",
        "scraping ecommerce reviews by sentiment",
        "automating pdf data extraction",
        "scraping price history for competitors",
        "scraping public datasets with rate limits",
        "legal considerations for web scraping"
    ],
    "smartphones": [
        "flagship android phones with best cameras",
        "compact smartphones with powerful specs",
        "budget 5G smartphones under $400",
        "smartphones with long-lasting batteries",
        "gaming smartphones with cooling systems",
        "phones with expandable storage options",
        "phones compatible with eSIM only",
        "rugged smartphones for outdoor work",
        "smartphones supporting wireless charging",
        "phones with high refresh rate displays",
        "smartphones optimized for photography",
        "best phones for seniors with large icons",
        "smartphones with stylus support",
        "dual-sim smartphones for travel",
        "foldable smartphones second generation",
        "android phones with clean UI",
        "smartphones with macro camera lenses",
        "phones with top-notch low-light performance",
        "best unlocked phones for global travel",
        "smartphones with fast wired charging"
    ],
    "tablets": [
        "tablets for digital art and drawing",
        "affordable tablets for kids",
        "android tablets with keyboard support",
        "tablets with LTE connectivity",
        "tablets for note-taking in college",
        "tablets for watching movies on flights",
        "tablets with desktop-like productivity",
        "tablets compatible with microsoft office",
        "tablets with AMOLED displays",
        "tablets optimized for gaming",
        "tablets with expandable storage",
        "budget tablets with parental controls",
        "tablets with strong battery life",
        "tablets for reading comics and manga",
        "tablets supporting stylus tilt sensitivity",
        "tablets with fast charging capability",
        "tablets that double as smart displays",
        "tablets for field inspections",
        "tablets with dual speakers",
        "tablets for travelers with GPS"
    ],
    "smart_home": [
        "smart thermostats compatible with alexa",
        "smart plugs with energy monitoring",
        "smart lighting starter kits",
        "smart home hubs with zigbee support",
        "smart locks with biometric authentication",
        "smart blinds that work with homekit",
        "smart garage door controllers",
        "smart irrigation controllers for lawns",
        "smart ceiling fans with voice control",
        "smart leak detectors for basements",
        "smart smoke and carbon monoxide alarms",
        "smart video doorbells with local storage",
        "smart home security systems under $500",
        "smart switches for multi-way circuits",
        "smart air purifiers with app control",
        "smart home starter bundles",
        "smart sensors for windows and doors",
        "smart pet feeders with cameras",
        "smart home products supporting matter",
        "smart hubs with local automation"
    ],
    "gaming_consoles": [
        "latest next-gen consoles availability",
        "bundle deals for playstation 5",
        "xbox series x accessories",
        "nintendo switch family bundles",
        "retro gaming consoles for nostalgia",
        "handheld gaming consoles with AAA titles",
        "cloud gaming compatible controllers",
        "consoles with VR support",
        "gaming console subscription comparisons",
        "portable dock alternatives for switch",
        "best external storage for consoles",
        "controllers with back paddles",
        "console racing wheel bundles",
        "gaming headsets compatible with consoles",
        "elite controllers for competitive play",
        "charging docks for console controllers",
        "console skins and customization kits",
        "family-friendly console games",
        "console game pass deals",
        "gaming console streaming accessories"
    ],
    "wearables": [
        "fitness trackers with GPS",
        "smartwatches for android users",
        "wearables with ECG monitoring",
        "sleep tracking wearables with insights",
        "budget fitness bands under $100",
        "smart rings with health metrics",
        "wearables with blood oxygen monitoring",
        "smart glasses with audio",
        "wearables for swimming laps",
        "wearables with stress monitoring",
        "wearables for kids with geofencing",
        "smartwatches with LTE connectivity",
        "wearables with long battery life",
        "wearables supporting contactless payments",
        "wearables for hiking and navigation",
        "fitness trackers with coaching programs",
        "wearables with menstrual cycle tracking",
        "wearables compatible with strava",
        "smart jewelry for wellness tracking",
        "wearables with fall detection"
    ],
    "drones": [
        "drones with 4K stabilized cameras",
        "beginner-friendly drones with obstacle avoidance",
        "compact foldable drones for travel",
        "drones for aerial mapping",
        "drones with long flight time",
        "drones suitable for indoor filming",
        "drones with thermal imaging",
        "fpv drones for racing",
        "drones with follow-me mode",
        "drones for agriculture crop monitoring",
        "drones with live streaming capability",
        "drones with interchangeable payloads",
        "drones for real estate photography",
        "drones with geofencing compliance",
        "drones with quiet propellers",
        "drones that can carry action cameras",
        "drones with return-to-home accuracy",
        "drones for search and rescue",
        "drones for classroom STEM kits",
        "drones with beginner training modes"
    ],
    "monitors": [
        "4K monitors with HDR support",
        "ultrawide monitors for productivity",
        "gaming monitors with 144Hz refresh rate",
        "color accurate monitors for designers",
        "portable monitors with usb-c",
        "monitors with built-in docking stations",
        "budget monitors under $200",
        "monitors with adjustable stands",
        "monitors for dual-screen setups",
        "monitors with integrated webcams",
        "curved monitors for immersive gaming",
        "monitors with KVM switch functionality",
        "monitors for photo editing under $500",
        "monitors with eye-care features",
        "monitors supporting daisy chaining",
        "monitors for console gaming",
        "touchscreen monitors for kiosks",
        "monitors with high color gamut",
        "monitors for trading setups",
        "monitors compatible with macbooks"
    ],
    "keyboards": [
        "mechanical keyboards with hot-swappable switches",
        "wireless keyboards with backlighting",
        "ergonomic keyboards for office use",
        "compact 60 percent keyboards",
        "keyboards with programmable macros",
        "budget mechanical keyboards under $100",
        "low-profile mechanical keyboards",
        "keyboards with quiet switches",
        "keyboards with multi-device pairing",
        "keyboards for gaming with RGB",
        "ortholinear keyboards for enthusiasts",
        "split keyboards for ergonomic typing",
        "keyboards with customizable keycaps",
        "mechanical keyboards with knob controls",
        "keyboards with built-in wrist rests",
        "keyboards designed for writers",
        "keyboards compatible with tablets",
        "water-resistant keyboards",
        "mechanical keyboards for Mac layout",
        "wireless numpad add-ons"
    ],
    "mice": [
        "ergonomic mice for wrist pain",
        "wireless gaming mice with low latency",
        "vertical mice for office work",
        "trackball mice for precision control",
        "lightweight mice under 70 grams",
        "mice with customizable DPI settings",
        "mice for graphic designers",
        "mice with multi-device switching",
        "left-handed gaming mice",
        "mice with USB-C charging",
        "mice with long battery life",
        "silent click mice for quiet offices",
        "mice with adjustable weights",
        "mice for laptop travelers",
        "mice with Bluetooth and dongle combo",
        "ambidextrous gaming mice",
        "mice with RGB lighting",
        "trackpad alternatives for PCs",
        "budget mice for students",
        "mice with programmable side buttons"
    ],
    "networking": [
        "wifi 6 routers for large homes",
        "mesh networking systems",
        "budget routers under $100",
        "routers with parental controls",
        "routers for gigabit internet",
        "modem router combo units",
        "network switches with PoE",
        "vpn routers for remote workers",
        "routers supporting multi-gig wan",
        "wifi extenders with ethernet ports",
        "network attached storage setups",
        "routers with built-in security",
        "travel routers for hotel wifi",
        "4G LTE routers for backup internet",
        "routers with app-based management",
        "routers supporting matter protocol",
        "routers optimized for gaming",
        "small business networking bundles",
        "home lab networking gear",
        "routers with USB file sharing"
    ],
    "printers": [
        "wireless color laser printers",
        "budget inkjet printers for home",
        "all-in-one printers with fax",
        "portable printers for photos",
        "printers with refillable ink tanks",
        "printers with automatic duplexing",
        "printers for small businesses",
        "printers with voice assistant integration",
        "printers with eco-friendly cartridges",
        "printers that support A3 paper",
        "printers optimized for labels",
        "printers with fast ppm speeds",
        "printers with mobile app support",
        "printers for crafting and scrapbooking",
        "printers with secure printing",
        "printers with low running costs",
        "printers supporting sublimation",
        "printers for students",
        "printers compatible with chromebooks",
        "printers with large touchscreens"
    ],
    "storage": [
        "NVMe SSDs with high endurance",
        "portable SSDs for photographers",
        "external hard drives with encryption",
        "network attached storage for home",
        "budget SSD upgrades for laptops",
        "USB flash drives with USB-C",
        "RAID enclosures for small offices",
        "memory cards for 8K video",
        "backup drives for mac users",
        "storage drives with rugged design",
        "NAS drives with Plex support",
        "storage expansion cards for consoles",
        "high capacity microSD cards",
        "cloud storage services comparison",
        "SSD heatsinks for PS5",
        "portable drives with fingerprint lock",
        "storage solutions for video editors",
        "enterprise storage arrays",
        "budget NAS setups",
        "external drives with Thunderbolt 4"
    ],
    "smart_tvs": [
        "4K smart TVs with Dolby Vision",
        "budget smart TVs under $500",
        "smart TVs with built-in soundbars",
        "smart TVs compatible with Alexa",
        "smart TVs supporting Apple AirPlay",
        "smart TVs with HDMI 2.1",
        "smart TVs optimized for gaming",
        "smart TVs with mini-LED backlighting",
        "smart TVs for bright rooms",
        "smart TVs with ambient modes",
        "smart TVs with art display features",
        "smart TVs with integrated Chromecast",
        "smart TVs for outdoor patios",
        "smart TVs with local dimming",
        "smart TVs with voice remote",
        "smart TVs with thin bezels",
        "smart TVs with multi-view",
        "smart TVs for RV setups",
        "smart TVs supporting matter",
        "smart TVs with OLED panels"
    ],
    "fitness_equipment": [
        "adjustable dumbbells for home gyms",
        "compact treadmills for apartments",
        "rowing machines with interactive classes",
        "exercise bikes with virtual rides",
        "home gym resistance band sets",
        "smart jump ropes with app tracking",
        "kettlebell sets with storage racks",
        "pilates reformers for home use",
        "elliptical machines with incline",
        "smart mirrors for workouts",
        "strength training systems with cables",
        "foldable benches for small spaces",
        "yoga mats with alignment guides",
        "battle ropes for HIIT training",
        "home sauna kits",
        "under desk ellipticals",
        "compact smith machines",
        "foam rollers for recovery",
        "weighted vests for running",
        "fitness trackers for strength workouts"
    ],
    "appliances": [
        "energy-efficient refrigerators",
        "compact washer dryer combos",
        "smart dishwashers with wifi",
        "induction cooktops with safety features",
        "air conditioners for small rooms",
        "portable air purifiers",
        "robot vacuums with mapping",
        "air fryers with dual baskets",
        "smart ovens with voice control",
        "countertop ice makers",
        "humidifiers for large rooms",
        "dehumidifiers with continuous drain",
        "espresso machines with milk frothers",
        "slow cookers with programmable timers",
        "blenders for smoothies and soups",
        "microwaves with convection",
        "smart washers with app alerts",
        "compact dishwashers for apartments",
        "wine coolers with dual zones",
        "water heaters with smart monitoring"
    ],
    "kitchen_gadgets": [
        "multi-cookers with pressure and air fry",
        "smart kitchen scales",
        "sous vide machines with wifi",
        "high-speed blenders for nut butter",
        "food processors with dough blades",
        "knife sets with self-sharpening blocks",
        "cast iron skillets with enamel coating",
        "non-stick pans free of PFOA",
        "smart meat thermometers",
        "compact dish racks",
        "reusable silicone food bags",
        "automatic pan stirrers",
        "kitchen composters with odor control",
        "bread makers with gluten-free settings",
        "electric kettles with variable temperature",
        "coffee grinders with burr grinders",
        "smart refrigerators with touch screens",
        "magnetic spice rack systems",
        "air-tight food storage containers",
        "kitchen timers with multiple presets"
    ],
    "furniture": [
        "ergonomic office chairs under $300",
        "standing desks with memory presets",
        "modular sofas for small apartments",
        "storage beds with drawers",
        "recliners with USB charging",
        "accent chairs with mid-century design",
        "dining tables with extendable leaves",
        "bookcases with adjustable shelves",
        "TV stands with cable management",
        "coffee tables with lift tops",
        "outdoor patio sets with cushions",
        "space-saving folding chairs",
        "gaming chairs with lumbar support",
        "wardrobes with mirrored doors",
        "bar carts with locking wheels",
        "entryway benches with storage",
        "nursery gliders with ottoman",
        "bean bag chairs for teens",
        "home office storage cabinets",
        "furniture with sustainable materials"
    ],
    "outdoor_gear": [
        "camping tents for four seasons",
        "sleeping bags rated for cold weather",
        "portable camp stoves",
        "hiking backpacks with hydration",
        "lightweight hiking boots",
        "camping lanterns with USB charging",
        "water filters for backpacking",
        "inflatable kayaks for beginners",
        "multi-tools for camping",
        "compact folding chairs for camping",
        "trekking poles for hiking",
        "camping cookware sets",
        "camping hammocks with bug nets",
        "portable solar panels for camping",
        "camp coolers with long ice retention",
        "outdoor survival kits",
        "mountain bikes for trails",
        "portable fire pits",
        "trail running hydration vests",
        "outdoor GPS devices"
    ],
    "security_devices": [
        "wireless security cameras",
        "video doorbells with local storage",
        "smart locks with fingerprint access",
        "alarm systems for apartments",
        "indoor cameras with pan tilt",
        "outdoor floodlight cameras",
        "security cameras with solar panels",
        "home security starter kits",
        "security sensors for windows",
        "garage security systems",
        "security cameras with two-way audio",
        "security devices with LTE backup",
        "motion sensors with pet immunity",
        "security keypads with touchscreens",
        "smart safes with biometric locks",
        "security cameras with AI detection",
        "door sensors with instant alerts",
        "security cameras with color night vision",
        "outdoor sirens for home security",
        "security cameras with battery backup"
    ],
    "automotive_accessories": [
        "dash cams with 4K recording",
        "bluetooth car adapters",
        "smart tire pressure monitors",
        "portable jump starters",
        "car seat organizers",
        "wireless car chargers",
        "backup cameras for older cars",
        "car infotainment upgrade kits",
        "car cleaning kits with foam cannons",
        "roof racks for road trips",
        "car refrigerators for camping",
        "car vacuum cleaners",
        "OBD2 scanners with app support",
        "portable air compressors for cars",
        "heated car seat covers",
        "car dash displays for navigation",
        "car security steering wheel locks",
        "portable car inverters",
        "car dash mounts for tablets",
        "LED headlights upgrade kits"
    ],
    "beauty_tools": [
        "hair dryers with ionic technology",
        "curling irons with adjustable heat",
        "straightening brushes for thick hair",
        "LED face masks for skincare",
        "microcurrent facial devices",
        "at-home laser hair removal kits",
        "manicure sets with UV lamp",
        "facial cleansing brushes",
        "jade rollers and gua sha sets",
        "travel makeup brush sets",
        "portable vanity mirrors with lights",
        "scalp massagers for hair growth",
        "hair clippers for home use",
        "body exfoliating brushes",
        "hot air stylers for volume",
        "electric toothbrushes with pressure sensors",
        "facial steamers with essential oil trays",
        "eyebrow trimmers with precision tips",
        "makeup organizers with drawers",
        "skin analysis devices"
    ],
    "health_devices": [
        "smart scales with body composition",
        "blood pressure monitors with bluetooth",
        "pulse oximeters with app sync",
        "portable ECG monitors",
        "smart thermometers with tracking",
        "air quality monitors for homes",
        "sleep tracking devices",
        "portable nebulizers",
        "hearing aids with rechargeable batteries",
        "wearable posture correctors",
        "UV sterilizers for personal items",
        "portable massagers for travel",
        "infrared light therapy devices",
        "smart inhalers with reminders",
        "digital pill dispensers",
        "smart humidifiers with sensors",
        "portable TENS units",
        "smart water bottles with hydration tracking",
        "blue light blocking glasses",
        "smart baby monitors with breathing tracking"
    ],
    "office_supplies": [
        "ergonomic office chairs",
        "standing desk converters",
        "desk organizers with cable management",
        "noise cancelling office dividers",
        "whiteboards with magnetic surfaces",
        "desk lamps with wireless charging",
        "office label makers",
        "document scanners with duplex",
        "paper shredders with cross-cut",
        "conference speakerphones",
        "monitor arms for dual setups",
        "desktop filing cabinets",
        "office plants for low light",
        "anti-fatigue mats for standing desks",
        "desk pads with mouse surface",
        "stationery sets for executive gifting",
        "office projectors for presentations",
        "cable trays for desks",
        "office storage boxes",
        "desk clocks with timers"
    ]
}


def get_all_prompts():
    """Return a flat list of all prompts."""
    all_prompts = []
    for prompts in PROMPT_CATEGORIES.values():
        all_prompts.extend(prompts)
    return all_prompts


def get_prompts_by_category():
    """Return the dictionary of prompts categorized."""
    return PROMPT_CATEGORIES


def get_timestamp():
    """Return a current timestamp string suitable for filenames."""
    return datetime.now().strftime("%Y-%m-%d_%H-%M")